# .github/release.yml

changelog:
  categories:
    - title: 🎉 Exciting New Features
      labels:
        - frontend
        - backend
    - title: 🐞 Bug fixes
      labels:
        - bugs
    - title: 🐞 Optimisations
      labels:
        - infrastructure
    - title: 🏡 Housekeeping and dependencies
      labels:
        - housekeeping
        - dependencies
        - migrations
