version: '3.9'

networks:
    in-meal-network:
        driver: bridge

services:
    inmeal-backend:
        container_name: inmeal-backend
        image: inmeal-backend
        restart: unless-stopped
        ports:
            - '${API_PORT}:7078'
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
            ASPNETCORE_URLS: 'http://+:7078'
            ConnectionStrings__InMealDbConnection: ${DATABASE_CONNECTION}
            ConnectionStrings__ServerVersionMajor: ${DATABASE_VERSION_MAJOR}
            ConnectionStrings__ServerVersionMinor: ${DATABASE_VERSION_MINOR}
            ConnectionStrings__ServerVersionBuild: ${DATABASE_VERSION_BUILD}
        networks:
            - in-meal-network
    inmeal-frontend:
        container_name: inmeal-frontend
        image: inmeal-frontend
        restart: unless-stopped
        ports:
            - '${SPA_PORT}:80'
        depends_on:
            - inmeal-backend
        networks:
            - in-meal-network
