version: '3.9'

networks:
    in-meal-network:
        driver: bridge

services:
    inmeal-backend:
        container_name: inmeal-backend
        image: inmeal/backend
        build:
            dockerfile: ./apps/InMeal.Api/Dockerfile
        restart: unless-stopped
        ports:
            - '${API_PORT}:7078'
        environment:
            ASPNETCORE_URLS: 'http://+:7078'
            ConnectionStrings__InMealDbConnection: ${DATABASE_CONNECTION}
            ConnectionStrings__ServerVersionMajor: ${DATABASE_VERSION_MAJOR}
            ConnectionStrings__ServerVersionMinor: ${DATABASE_VERSION_MINOR}
            ConnectionStrings__ServerVersionBuild: ${DATABASE_VERSION_BUILD}
            GenerativeRecipeImageMicroservice__ServiceUrl: ${MICROSERVICE_URL}
        networks:
            - in-meal-network
    inmeal-frontend:
        container_name: inmeal-frontend
        image: inmeal/frontend
        build:
            dockerfile: ./apps/fui/Dockerfile
        restart: unless-stopped
        ports:
            - '${SPA_PORT}:80'
        depends_on:
            - inmeal-backend
            - inmeal-generative-recipe-images
        networks:
            - in-meal-network
    inmeal-generative-recipe-images:
        container_name: inmeal-gri
        image: inmeal/gri
        restart: unless-stopped
        ports:
            - '${MICROSERVICE_PORT}:8131'
        environment:
            ENVIRONMENT: 'production'
        build:
            context: ./apps/gri
        networks:
            - in-meal-network
