version: '3.9'

networks:
    in-meal-network:
        driver: bridge

services:
    inmeal:
        container_name: inmeal
        image: inmeal
        restart: unless-stopped
        ports:
            - '${SPA_PORT}:80'
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
            ASPNETCORE_URLS: 'http://+:7078'
            ConnectionStrings__InMealDbConnection: ${DATABASE_CONNECTION}
            ConnectionStrings__ServerVersionMajor: ${DATABASE_VERSION_MAJOR}
            ConnectionStrings__ServerVersionMinor: ${DATABASE_VERSION_MINOR}
            ConnectionStrings__ServerVersionBuild: ${DATABASE_VERSION_BUILD}
        networks:
            - in-meal-network
