version: '3.9'

services:
    api:
        restart: unless-stopped
        build: .
        ports:
            - '${API_PORT}:7078'
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
            ASPNETCORE_URLS: 'http://+:7078'
            DATABASE_CONNECTION: ${DATABASE_CONNECTION}
