version: '3.9'

services:
    inmeal-api:
        container_name: api
        restart: unless-stopped
        build:
            context: .
        ports:
            - '${API_PORT}:${API_PORT}'
        environment:
            DATABASE_CONNECTION: '${DATABASE_CONNECTION}'
            ASPNETCORE_ENVIRONMENT: 'Production'
            ASPNETCORE_URLS: 'http://+:${API_PORT}'
