version: '3.9'

secrets:
    database_connection:
        file: db_connection.secret

services:
    inmeal-api:
        container_name: api
        restart: unless-stopped
        build:
            context: .
        ports:
            - '${API_PORT}:7078'
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
            ASPNETCORE_URLS: 'http://+:7078'
        secrets:
            - database_connection
