name: 'Pull Request Labeler'
on:
    push:
        branches-ignore:
            - 'master'
            - 'untracked/**'
    pull_request:
        branches-ignore:
            - 'master'
            - 'untracked/**'

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v5
